package com.crosspaste.paste

/**
 * Clipboard hints password managers attach to secrets so clipboard managers
 * skip them (Bitwarden, 1Password, KeePassXC and others all follow these
 * conventions). Content carrying a hint must not be recorded or synced.
 *
 * Per platform:
 *  - Windows: the registered formats `ExcludeClipboardContentFromMonitorProcessing`
 *    or `Clipboard Viewer Ignore` (KeePass 2.x; presence alone is the signal), or
 *    `CanIncludeInClipboardHistory` holding a DWORD `0`. Bitwarden writes only the
 *    latter, so the value must be read. `CanUploadToCloudClipboard` alone is
 *    deliberately ignored: it only opts out of cross-device sync while still
 *    allowing local history, and no known password manager relies on it by itself.
 *  - macOS: the pasteboard types `org.nspasteboard.ConcealedType`,
 *    `org.nspasteboard.TransientType`, `org.nspasteboard.AutoGeneratedType` and
 *    `com.agilebits.onepassword`, checked natively in `MacosApi.swift`.
 *  - Linux: the X11 selection target `x-kde-passwordManagerHint`.
 */
object PasswordManagerHints {

    const val WINDOWS_EXCLUDE_FROM_MONITORING = "ExcludeClipboardContentFromMonitorProcessing"

    const val WINDOWS_CLIPBOARD_VIEWER_IGNORE = "Clipboard Viewer Ignore"

    const val WINDOWS_CAN_INCLUDE_IN_HISTORY = "CanIncludeInClipboardHistory"

    const val LINUX_PASSWORD_MANAGER_HINT = "x-kde-passwordManagerHint"

    fun isConcealedOnWindows(probe: WindowsClipboardFormatProbe): Boolean {
        if (probe.isFormatAvailable(WINDOWS_EXCLUDE_FROM_MONITORING) ||
            probe.isFormatAvailable(WINDOWS_CLIPBOARD_VIEWER_IGNORE)
        ) {
            return true
        }
        if (probe.isFormatAvailable(WINDOWS_CAN_INCLUDE_IN_HISTORY)) {
            // Fail safe: whoever writes this format wants to steer history, and
            // nearly always to opt out. If the value cannot be read right now
            // (clipboard held by another process), skipping one item is cheaper
            // than recording a secret.
            if ((probe.readDword(WINDOWS_CAN_INCLUDE_IN_HISTORY) ?: 0) == 0) {
                return true
            }
        }
        return false
    }

    fun isConcealedOnLinux(targets: List<String>): Boolean = LINUX_PASSWORD_MANAGER_HINT in targets
}

/** Minimal view of the Windows clipboard needed to evaluate the hints. */
interface WindowsClipboardFormatProbe {

    fun isFormatAvailable(name: String): Boolean

    /** Reads a DWORD-valued format; null when it is absent or cannot be read right now. */
    fun readDword(name: String): Int?
}
