@file:Suppress("DEPRECATION", "DEPRECATION_ERROR")

import java.io.FileReader
import java.util.Properties

val versionProperties = Properties()
versionProperties.load(
    FileReader(
        project.projectDir
            .toPath()
            .parent
            .resolve("app/src/desktopMain/resources/crosspaste-version.properties")
            .toFile(),
    ),
)

group = "com.crosspaste"
version = versionProperties.getProperty("version")

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.ktlint)
}

ktlint {
    verbose = true
    android = false
    ignoreFailures = false
    filter {
        exclude { element ->
            val path = element.file.path
            path.contains("\\generated\\") || path.contains("/generated/")
        }
    }
}

// The CLI binary must report the same version as the app it ships with.
// CI can override via -PcliVersion (the release workflow derives the full
// version from the git tag before the version file is rewritten).
val cliVersionValue = (project.findProperty("cliVersion") as? String) ?: versionProperties.getProperty("version")

val generateCliVersion by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/cliVersion/kotlin")
    inputs.property("cliVersion", cliVersionValue)
    outputs.dir(outputDir)
    doLast {
        val file =
            outputDir
                .get()
                .asFile
                .resolve("com/crosspaste/cli/commands/CliVersion.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by :cli:generateCliVersion — do not edit.
            |package com.crosspaste.cli.commands
            |
            |const val CLI_VERSION: String = "$cliVersionValue"
            |
            """.trimMargin(),
        )
    }
}

kotlin {
    val hostOs = System.getProperty("os.name")
    val isArm64 = System.getProperty("os.arch") == "aarch64"
    val isMingwX64 = hostOs.startsWith("Windows")

    val cliTarget = project.findProperty("cli.target") as? String
    val isMacosTarget =
        when (cliTarget) {
            "macosArm64", "macosX64" -> true
            null -> hostOs == "Mac OS X"
            else -> false
        }

    val nativeTarget =
        if (cliTarget != null) {
            when (cliTarget) {
                "macosArm64" -> macosArm64("cliNative")
                "macosX64" -> macosX64("cliNative")
                "linuxArm64" -> linuxArm64("cliNative")
                "linuxX64" -> linuxX64("cliNative")
                "mingwX64" -> mingwX64("cliNative")
                else -> throw GradleException("Unsupported CLI target: $cliTarget")
            }
        } else {
            when {
                hostOs == "Mac OS X" && isArm64 -> macosArm64("cliNative")
                hostOs == "Mac OS X" && !isArm64 -> macosX64("cliNative")
                hostOs == "Linux" && isArm64 -> linuxArm64("cliNative")
                hostOs == "Linux" && !isArm64 -> linuxX64("cliNative")
                isMingwX64 -> mingwX64("cliNative")
                else -> throw GradleException("Host OS is not supported in Kotlin/Native.")
            }
        }

    nativeTarget.apply {
        compilations.getByName("main") {
            cinterops {
                val execpath by creating
            }
        }
        binaries {
            executable {
                entryPoint = "com.crosspaste.cli.main"
                baseName = "crosspaste-cli"
                // Workaround for Clikt duplicate symbol bug in Kotlin/Native
                // See: https://github.com/ajalt/clikt/issues/598
                // Apple ld does not support --allow-multiple-definition (GNU ld only)
                if (!isMacosTarget) {
                    linkerOpts("--allow-multiple-definition")
                }
            }
        }
    }

    // Platform-split sources keyed on the selected target (not the host,
    // which would break -Pcli.target cross-compilation)
    val isMingwTarget = cliTarget == "mingwX64" || (cliTarget == null && isMingwX64)

    sourceSets {
        val cliNativeMain by getting {
            kotlin.srcDir(generateCliVersion)
            if (isMingwTarget) {
                kotlin.srcDir("src/mingwNativeMain/kotlin")
            } else {
                kotlin.srcDir("src/posixNativeMain/kotlin")
            }
            dependencies {
                implementation(libs.clikt)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.cio)
                implementation(libs.okio)
            }
        }
    }
}
