@file:Suppress("DEPRECATION", "DEPRECATION_ERROR")

import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.NativeBuildType
import org.jetbrains.kotlin.konan.target.Family
import org.jetbrains.kotlin.konan.target.HostManager
import java.io.FileReader
import java.util.Properties

val versionProperties = Properties()
versionProperties.load(
    FileReader(
        project.projectDir
            .toPath()
            .parent
            .resolve("app/src/desktopMain/resources/crosspaste-version.properties")
            .toFile(),
    ),
)

group = "com.crosspaste"
version = versionProperties.getProperty("version")

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.ktlint)
}

ktlint {
    verbose = true
    android = false
    ignoreFailures = false
    filter {
        exclude { element ->
            val path = element.file.path
            path.contains("\\generated\\") || path.contains("/generated/")
        }
    }
}

// The CLI binary must report the same version as the app it ships with.
// CI can override via -PcliVersion (the release workflow derives the full
// version from the git tag before the version file is rewritten).
val cliVersionValue = (project.findProperty("cliVersion") as? String) ?: versionProperties.getProperty("version")

val generateCliVersion =
    tasks.register("generateCliVersion") {
        val outputDir = layout.buildDirectory.dir("generated/cliVersion/kotlin")
        inputs.property("cliVersion", cliVersionValue)
        outputs.dir(outputDir)
        doLast {
            val file =
                outputDir
                    .get()
                    .asFile
                    .resolve("com/crosspaste/cli/commands/CliVersion.kt")
            file.parentFile.mkdirs()
            file.writeText(
                """
            |// Generated by :cli:generateCliVersion — do not edit.
            |package com.crosspaste.cli.commands
            |
            |const val CLI_VERSION: String = "$cliVersionValue"
            |
                """.trimMargin(),
            )
        }
    }

kotlin {
    // All five release targets are declared statically so a single Gradle
    // invocation can build every target the host toolchain supports (Apple
    // targets need a macOS host; everything else cross-compiles from any
    // host). Targets unsupported on the current host are disabled by the
    // Kotlin plugin with a warning and simply skipped.
    val cliTargets =
        listOf(
            macosArm64(),
            macosX64(),
            linuxX64(),
            linuxArm64(),
            mingwX64(),
        )

    cliTargets.forEach { target ->
        val isMacosTarget = target.konanTarget.family == Family.OSX
        val isMingwTarget = target.konanTarget.family == Family.MINGW

        target.compilations.getByName("main") {
            cinterops {
                create("execpath")
                create("secretinput")
            }
        }
        // Workaround for Clikt duplicate symbol bug in Kotlin/Native
        // See: https://github.com/ajalt/clikt/issues/598
        // Apple ld does not support --allow-multiple-definition (GNU ld only).
        // Konan invokes the linker directly for Linux targets (bare flag) but
        // goes through the clang++ driver for mingw, which needs -Wl, to
        // forward the flag.
        val allowMultipleDefinition =
            when {
                isMacosTarget -> null
                isMingwTarget -> "-Wl,--allow-multiple-definition"
                else -> "--allow-multiple-definition"
            }

        target.binaries {
            executable {
                entryPoint = "com.crosspaste.cli.main"
                baseName = "crosspaste-cli"
                allowMultipleDefinition?.let { linkerOpts(it) }
            }
            // The test binary needs the same Clikt duplicate-symbol workaround;
            // GNU ld only hits it when konan compiler caches are enabled (host
            // builds), which is why cross-links from macOS don't reproduce it
            allowMultipleDefinition?.let { getTest("debug").linkerOpts(it) }
        }

        // The CLI sources predate the five-target split and are written as
        // leaf sources (free use of target-specific APIs, no expect/actual),
        // so each target compiles the same source-directory union directly
        // instead of going through shared intermediate source sets.
        sourceSets.getByName("${target.name}Main") {
            kotlin.srcDir("src/cliNativeMain/kotlin")
            kotlin.srcDir(generateCliVersion)
            if (isMingwTarget) {
                kotlin.srcDir("src/mingwNativeMain/kotlin")
            } else {
                kotlin.srcDir("src/posixNativeMain/kotlin")
            }
        }
        sourceSets.getByName("${target.name}Test") {
            kotlin.srcDir("src/cliNativeTest/kotlin")
            if (!isMingwTarget) {
                kotlin.srcDir("src/posixNativeTest/kotlin")
            }
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.clikt)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.cio)
            implementation(libs.okio)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

// Runs the CLI test suite for the host's own target — a stable task name for
// CI and local use that doesn't depend on which machine invokes it.
val hostTestTaskName =
    kotlin.targets
        .withType<KotlinNativeTarget>()
        .firstOrNull { it.konanTarget == HostManager.host }
        ?.let { "${it.name}Test" }

tasks.register("cliNativeTest") {
    group = "verification"
    description = "Runs CLI tests for the host target."
    hostTestTaskName?.let { dependsOn(it) }
}

// Runs the debug CLI for the host target against the dev app instance
// (`./gradlew app:run`, whose user-data dir is app/.user) without packaging
// a release build. Usage: ./gradlew :cli:run --args="history -n 5"
// An explicit CROSSPASTE_USER_DATA_DIR in the caller's environment wins over
// the app/.user default, so the task can also target other instances.
abstract class CliRunTask : Exec() {
    @get:Input
    @get:org.gradle.api.tasks.options.Option(
        option = "args",
        description = "Arguments passed to the CLI (whitespace-separated; quote to group)",
    )
    abstract val cliArgs: Property<String>

    init {
        cliArgs.convention("")
    }

    companion object {
        // Quote-aware whitespace tokenizer matching Gradle's own
        // JavaExec.setArgsString() semantics (ArgumentsSplitter): single or
        // double quotes group text (including embedded mid-token quoting like
        // foo"bar baz"); an unterminated quote runs to the end of the string.
        fun splitArgs(argsString: String): List<String> {
            val tokens = mutableListOf<String>()
            val current = StringBuilder()
            var quote: Char? = null
            var inToken = false
            for (c in argsString) {
                when {
                    quote != null ->
                        if (c == quote) quote = null else current.append(c)
                    c == '"' || c == '\'' -> {
                        quote = c
                        inToken = true
                    }
                    c.isWhitespace() -> {
                        if (inToken) {
                            tokens.add(current.toString())
                            current.setLength(0)
                            inToken = false
                        }
                    }
                    else -> {
                        current.append(c)
                        inToken = true
                    }
                }
            }
            if (inToken) tokens.add(current.toString())
            return tokens
        }
    }
}

kotlin.targets
    .withType<KotlinNativeTarget>()
    .firstOrNull { it.konanTarget == HostManager.host }
    ?.let { hostTarget ->
        val debugExecutable = hostTarget.binaries.getExecutable(NativeBuildType.DEBUG)
        tasks.register<CliRunTask>("run") {
            group = "application"
            description = "Runs the debug CLI against the dev app started with ./gradlew app:run."
            dependsOn(debugExecutable.linkTaskProvider)
            executable(debugExecutable.outputFile.absolutePath)
            standardInput = System.`in`
            // The CLI uses non-zero exits as part of its contract (3 = app not
            // running, 2 = usage); don't turn those into Gradle build failures.
            // Anything else (internal error, crash, signal) still fails the
            // build — checked in doLast below.
            isIgnoreExitValue = true
            if (System.getenv("CROSSPASTE_USER_DATA_DIR").isNullOrBlank()) {
                environment(
                    "CROSSPASTE_USER_DATA_DIR",
                    rootProject.layout.projectDirectory
                        .dir("app/.user")
                        .asFile.absolutePath,
                )
            }
            doFirst {
                args(CliRunTask.splitArgs(cliArgs.get()))
            }
            doLast {
                val exitValue = executionResult.get().exitValue
                if (exitValue !in setOf(0, 2, 3)) {
                    throw GradleException("CLI exited with unexpected exit code $exitValue")
                }
            }
        }
    }

// Collects release executables under cli/dist/<target>/crosspaste-cli(.exe),
// the layout the packaging pipeline (Conveyor + release workflow) consumes.
kotlin.targets.withType<KotlinNativeTarget>().forEach { target ->
    val capitalizedName = target.name.replaceFirstChar { it.uppercase() }
    val executable = target.binaries.getExecutable(NativeBuildType.RELEASE)
    tasks.register<Copy>("assembleDist$capitalizedName") {
        group = "distribution"
        description = "Copies the ${target.name} release executable to cli/dist/${target.name}/."
        dependsOn(executable.linkTaskProvider)
        from(executable.outputFile)
        into(layout.projectDirectory.dir("dist/${target.name}"))
        // Kotlin/Native emits crosspaste-cli.kexe on POSIX targets;
        // ship it under the bare command name (mingw keeps .exe)
        rename { name -> name.removeSuffix(".kexe") }
    }
}

tasks.register("assembleDist") {
    group = "distribution"
    description = "Builds CLI release executables for every target the host can compile."
    // Explicit host → buildable-target map: Apple targets need a macOS host,
    // Linux hosts cross-compile everything else, Windows hosts build only
    // their own target. (HostManager.isEnabled is not used here: it reports
    // mingwX64 as disabled on macOS even though cross-linking it works.)
    kotlin.targets.withType<KotlinNativeTarget>().forEach { target ->
        val buildable =
            when {
                HostManager.hostIsMac -> true
                HostManager.hostIsLinux -> target.konanTarget.family != Family.OSX
                else -> target.konanTarget.family == Family.MINGW
            }
        if (buildable) {
            dependsOn("assembleDist${target.name.replaceFirstChar { it.uppercase() }}")
        }
    }
}
