name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as you can so we have a better chance of fixing the bug quickly. 
        Thanks for your contribution to improve this project!
  - type: dropdown
    id: frequency
    attributes:
      label: How frequently does the bug occur?
      options:
        - -- select --
        - Once
        - Sometimes
        - Always
    validations:
      required: true
  # Description
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe what you were expecting and what actually happened.
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Stacktrace & log output
      description: Please paste any relevant log output or stacktrace if you're getting an exception/crash.
      render: shell
  # Repro information
  - type: dropdown
    id: repro
    attributes:
      label: Can you reproduce the bug?
      options:
        - -- select --
        - Always
        - Sometimes
        - 'No'
    validations:
      required: true
  - type: textarea
    id: code-snippets
    attributes:
      label: Reproduction Steps
      description: |
        If you can reproduce the bug, please provide detailed steps for how WE can reproduce it.
  # Version
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of clipevery you're using, you can see it in Menu -> About.
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: OS
      description: Which system are you using clipevery under, Macos (intel or Apple silicon) / Windows / Linux.
    validations:
      required: true