#!/usr/bin/env python3
"""Regenerates the East Asian Wide interval table used by the CLI's
cell-width estimate (cli/.../commands/EastAsianWideRanges.kt).

Usage:
  curl -sfO https://www.unicode.org/Public/16.0.0/ucd/EastAsianWidth.txt
  python3 scripts/generate-cli-cell-width-table.py EastAsianWidth.txt \
      > cli/src/cliNativeMain/kotlin/com/crosspaste/cli/commands/EastAsianWideRanges.kt

Collects every codepoint with East_Asian_Width W (Wide) or F (Fullwidth),
unions the blocks whose *unassigned* codepoints also default to Wide (per the
file header), and emits merged intervals. Emoji_Presentation characters are a
subset of W/F since Unicode 9, so no separate emoji table is needed.
"""

import re
import sys

# Unassigned codepoints in these blocks default to Wide (EastAsianWidth.txt header).
DEFAULT_WIDE = [
    (0x3400, 0x4DBF),
    (0x4E00, 0x9FFF),
    (0xF900, 0xFAFF),
    (0x20000, 0x2FFFD),
    (0x30000, 0x3FFFD),
]

def main(path):
    ranges = list(DEFAULT_WIDE)
    version = "unknown"
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("# EastAsianWidth-"):
                version = line.split("-")[1].split(".txt")[0]
            line = line.split("#")[0].strip()
            if not line:
                continue
            m = re.match(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)", line)
            if not m:
                continue
            lo, hi, eaw = m.group(1), m.group(2) or m.group(1), m.group(3)
            if eaw in ("W", "F"):
                ranges.append((int(lo, 16), int(hi, 16)))

    ranges.sort()
    merged = []
    for lo, hi in ranges:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], hi))
        else:
            merged.append((lo, hi))

    print("// Generated by scripts/generate-cli-cell-width-table.py from")
    print(f"// EastAsianWidth.txt (Unicode {version}) - do not edit by hand.")
    print("package com.crosspaste.cli.commands")
    print()
    print("/**")
    print(" * Merged codepoint intervals with East_Asian_Width Wide or Fullwidth,")
    print(" * including blocks whose unassigned codepoints default to Wide, as")
    print(" * [start0, end0, start1, end1, ...] pairs sorted ascending.")
    print(" */")
    print("internal val EAST_ASIAN_WIDE_RANGES: IntArray =")
    print("    intArrayOf(")
    for lo, hi in merged:
        print(f"        0x{lo:04X}, 0x{hi:04X},")
    print("    )")

if __name__ == "__main__":
    main(sys.argv[1])
