package com.crosspaste.exception

val standardErrorCodeMap: Map<Int, ErrorCodeSupplier> =
    StandardErrorCode.entries.associateBy { it.getCode() }

enum class StandardErrorCode(
    code: Int,
    errorType: ErrorType,
) : ErrorCodeSupplier {
    UNKNOWN_ERROR(0, ErrorType.INTERNAL_ERROR),
    BOOTSTRAP_ERROR(1, ErrorType.INTERNAL_ERROR),
    INVALID_PARAMETER(2, ErrorType.USER_ERROR),
    NOT_FOUND_API(3, ErrorType.USER_ERROR),

    CANT_CREATE_DIR(100, ErrorType.INTERNAL_ERROR),
    CANT_CREATE_FILE(101, ErrorType.INTERNAL_ERROR),
    OUT_RANGE_CHUNK_INDEX(102, ErrorType.INTERNAL_ERROR),

    NOT_FOUND_APP_INSTANCE_ID(1000, ErrorType.EXTERNAL_ERROR),
    TOKEN_INVALID(1001, ErrorType.EXTERNAL_ERROR),
    NOT_FOUND_SOURCE(1002, ErrorType.EXTERNAL_ERROR),
    NOT_FOUND_ICON(1003, ErrorType.EXTERNAL_ERROR),
    CLEAN_PASTE_TASK_FAIL(1004, ErrorType.EXTERNAL_ERROR),
    DELETE_TASK_FAIL(1005, ErrorType.EXTERNAL_ERROR),
    HTML_2_IMAGE_TASK_FAIL(1006, ErrorType.EXTERNAL_ERROR),
    PULL_FILE_TASK_FAIL(1007, ErrorType.EXTERNAL_ERROR),
    PULL_FILE_CHUNK_TASK_FAIL(1008, ErrorType.EXTERNAL_ERROR),
    PULL_ICON_TASK_FAIL(1009, ErrorType.EXTERNAL_ERROR),
    NOT_FOUND_FILES_INDEX(1010, ErrorType.EXTERNAL_ERROR),
    NOT_MATCH_APP_INSTANCE_ID(1011, ErrorType.EXTERNAL_ERROR),
    CLEAN_TASK_FAIL(1012, ErrorType.EXTERNAL_ERROR),
    SWITCH_LANGUAGE_TASK_FAIL(1013, ErrorType.EXTERNAL_ERROR),
    OPEN_GRAPH_TASK_FAIL(1014, ErrorType.EXTERNAL_ERROR),

    SIGN_INVALID(2000, ErrorType.EXTERNAL_ERROR),
    EXCHANGE_FAIL(2001, ErrorType.EXTERNAL_ERROR),
    EXCHANGE_TIMEOUT(2002, ErrorType.EXTERNAL_ERROR),
    UNTRUSTED_IDENTITY(2003, ErrorType.EXTERNAL_ERROR),
    TRUST_FAIL(2005, ErrorType.EXTERNAL_ERROR),
    TRUST_TIMEOUT(2006, ErrorType.EXTERNAL_ERROR),
    ENCRYPT_FAIL(2007, ErrorType.INTERNAL_ERROR),
    DECRYPT_FAIL(2008, ErrorType.EXTERNAL_ERROR),

    SYNC_PASTE_ERROR(3000, ErrorType.EXTERNAL_ERROR),
    SYNC_PASTE_NOT_FOUND_RESOURCE(3001, ErrorType.EXTERNAL_ERROR),
    SYNC_PASTE_NOT_FOUND_DATA(3002, ErrorType.EXTERNAL_ERROR),

    REMOTE_SHOW_PAIRING_CODE_DISABLED(3100, ErrorType.USER_ERROR),

    // Pairing v3 wire errors (ai/docs/PAIRING_PROTOCOL_V3.md §15). Responses must not
    // disclose whether a guessed PIN was close or which sub-proof failed: proof-stage
    // failures all surface as PAIRING_PROOF_INVALID.
    PAIRING_DISABLED(3200, ErrorType.EXTERNAL_ERROR),
    PAIRING_VERSION_UNSUPPORTED(3201, ErrorType.EXTERNAL_ERROR),
    PAIRING_CIPHERSUITE_UNSUPPORTED(3202, ErrorType.EXTERNAL_ERROR),
    PAIRING_CAPACITY_EXCEEDED(3203, ErrorType.EXTERNAL_ERROR),
    PAIRING_RATE_LIMITED(3204, ErrorType.EXTERNAL_ERROR),
    PAIRING_SESSION_NOT_FOUND(3205, ErrorType.EXTERNAL_ERROR),
    PAIRING_SESSION_EXPIRED(3206, ErrorType.EXTERNAL_ERROR),
    PAIRING_SESSION_CONSUMED(3207, ErrorType.EXTERNAL_ERROR),
    PAIRING_PIN_EXPIRED(3208, ErrorType.EXTERNAL_ERROR),
    PAIRING_PROOF_INVALID(3209, ErrorType.EXTERNAL_ERROR),
    PAIRING_TRANSCRIPT_MISMATCH(3210, ErrorType.EXTERNAL_ERROR),
    PAIRING_IDENTITY_INVALID(3211, ErrorType.EXTERNAL_ERROR),
    PAIRING_INVALID_STATE(3212, ErrorType.EXTERNAL_ERROR),
    PAIRING_REJECTED(3213, ErrorType.EXTERNAL_ERROR),
    PAIRING_CANCELLED(3214, ErrorType.EXTERNAL_ERROR),

    SYNC_NOT_ALLOW_RECEIVE_BY_USER(4000, ErrorType.USER_ERROR),
    SYNC_NOT_ALLOW_SEND_BY_USER(4001, ErrorType.USER_ERROR),
    CANT_GET_SYNC_ADDRESS(4002, ErrorType.USER_ERROR),
    SYNC_NOT_ALLOW_RECEIVE_BY_APP(4003, ErrorType.INTERNAL_ERROR),
    SYNC_NOT_ALLOW_SEND_BY_APP(4004, ErrorType.INTERNAL_ERROR),

    EXPORT_FAIL(5000, ErrorType.INTERNAL_ERROR),
    IMPORT_FAIL(5001, ErrorType.INTERNAL_ERROR),

    CLI_FORBIDDEN(6000, ErrorType.EXTERNAL_ERROR),
    CLI_NOT_FOUND(6001, ErrorType.EXTERNAL_ERROR),
    CLI_INVALID_REQUEST(6002, ErrorType.EXTERNAL_ERROR),

    NOT_FOUND_PUSH_SESSION(7000, ErrorType.EXTERNAL_ERROR),
    PUSH_SESSION_REJECTED(7001, ErrorType.EXTERNAL_ERROR),
    PUSH_NOT_FILE_TYPE(7002, ErrorType.EXTERNAL_ERROR),
    PUSH_PREPARE_FAIL(7003, ErrorType.EXTERNAL_ERROR),
    PUSH_CHUNK_UPLOAD_FAIL(7004, ErrorType.EXTERNAL_ERROR),
    PUSH_COMPLETE_FAIL(7005, ErrorType.EXTERNAL_ERROR),
    PUSH_CHUNK_COUNT_MISMATCH(7006, ErrorType.EXTERNAL_ERROR),
    ;

    private val errorCode: ErrorCode = ErrorCode(code, name, errorType)

    override fun toErrorCode(): ErrorCode = errorCode

    fun getCode(): Int = errorCode.code
}
