name: Update Contributors

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Update contributors in README
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/scripts/update-contributors.sh ${{ github.repository }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ":construction_worker: update contributors in README"
          file_pattern: 'README.md README.zh-CN.md'
