package com.crosspaste.secure

import com.crosspaste.utils.CryptographyUtils
import com.crosspaste.utils.getCodecsUtils
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFails

class SecureMessageCipherTest {

    private val codecs = getCodecsUtils()

    @Test
    fun `peers decrypt each other's messages`() =
        runTest {
            val first = CryptographyUtils.generateSecureKeyPair()
            val second = CryptographyUtils.generateSecureKeyPair()
            val firstCipher =
                SecureMessageCipher(first.cryptKeyPair.privateKey, second.cryptKeyPair.publicKey)
            val secondCipher =
                SecureMessageCipher(second.cryptKeyPair.privateKey, first.cryptKeyPair.publicKey)
            val payload = "ws paste push payload".encodeToByteArray()

            assertContentEquals(payload, secondCipher.decrypt(firstCipher.encrypt(payload)))
            assertContentEquals(payload, firstCipher.decrypt(secondCipher.encrypt(payload)))
        }

    @Test
    fun `decrypt fails for a non-peer key pair`() =
        runTest {
            val first = CryptographyUtils.generateSecureKeyPair()
            val second = CryptographyUtils.generateSecureKeyPair()
            val third = CryptographyUtils.generateSecureKeyPair()
            val senderCipher =
                SecureMessageCipher(first.cryptKeyPair.privateKey, second.cryptKeyPair.publicKey)
            val strangerCipher =
                SecureMessageCipher(third.cryptKeyPair.privateKey, first.cryptKeyPair.publicKey)

            val ciphertext = senderCipher.encrypt("secret".encodeToByteArray())

            assertFails { strangerCipher.decrypt(ciphertext) }
        }

    /**
     * Fixed vector generated by this cipher on the JVM provider. Proves every
     * platform (including the WebCrypto backend used by the Chrome extension)
     * decrypts JVM-produced AES-CBC bytes, i.e. desktop `SecureMessageProcessor`
     * output stays readable across clients.
     */
    @Test
    fun `decrypts jvm-generated fixture`() =
        runTest {
            val serializer = SecureKeyPairSerializer()
            val receiverPrivate =
                serializer.decodeCryptPrivateKey(
                    codecs.base64Decode(
                        "MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCAIF20UYFtkADqKhkgwsxtHQnEs3VYS8CPZajyt8yq5kQ==",
                    ),
                )
            val senderPublic =
                serializer.decodeCryptPublicKey(
                    codecs.base64Decode(
                        "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoRc2R1Lgt4RhhwXIMKR7V0PxwC9dSB7/d4C7PcaYuR4mX0kOMXvR4vSY10Olp5RdYUVIdT/i/FtY7ODlBzrSqw==",
                    ),
                )
            val ciphertext =
                codecs.base64Decode(
                    "/oE+PuPy6qonhFKIWUnZVzw7FX4lT0YyWfiCyECHt1lSmNGQ0HAIZs9O6AUJ2XTByxqzeOHqEVQf3YX9ma4T2g==",
                )

            val cipher = SecureMessageCipher(receiverPrivate, senderPublic)

            assertEquals(
                "crosspaste-secure-message-cipher-fixture-v1",
                cipher.decrypt(ciphertext).decodeToString(),
            )
        }
}
